{{- if .Values.ui.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: siembol-storm-ui
  annotations:
    cert-manager.io/issuer: ca-issuer
spec:
  {{ if .Values.tls.enabled -}}
  tls:
  - hosts: 
    - {{ .Values.storm.ingress.hostname }}
    secretName: {{ include "siembol.ui.fullname" $ }}-tls
  {{ end }}
  rules:
  - host: {{ .Values.storm.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: siembol-storm-ui
            port: 
              number: 8080
{{- end -}}